- name: Single Node Kubernetes Cluster
  uses: CodingNagger/minikube-setup-action@v1.0.3
  with:
    # Minikube version to install
    minikube-version: # optional, default is 1.6.2
    # Kubernetes version to install
    k8s-version: # optional, default is 1.17.0
