name: "Cluster compliance using Minkube"
on: [pull_request, push]

jobs:
  minikube-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.11.0
        k8s-version: 1.15.1
    - uses: actions/checkout@master
      with:
        repository: jemueldalino/kube-bench
    - name: Testing
      run: |
        sudo snap remove minikube
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start
        minikube update-context
        kubectl cluster-info
        kubectl get pods -n kube-system
        kubectl apply -f job.yaml
        kubectl get pods | grep kube-bench
